<a href="https://colab.research.google.com/github/rsnehal0102/Movie-recommender/blob/main/MovieRecommender_System_Snehal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the libraries and neccessary cosine_simalirty function required

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data loading


In [2]:
movies_data = pd.read_csv('/content/movies.csv')

Sample 5 rows printing

In [3]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [4]:
movies_data.shape # printing the number of rows and columns

(4803, 24)

Selecting the required features

In [19]:
selected_features = ['genres','keywords','overview','cast','director']
print(selected_features)

['genres', 'keywords', 'overview', 'cast', 'director']


In [20]:
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [21]:
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['overview']+' '+movies_data['cast']+' '+movies_data['director']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [25]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 4207)	0.14134939369355703
  (0, 13932)	0.09005342709214369
  (0, 22773)	0.16033494305632573
  (0, 17493)	0.13142966756625357
  (0, 15307)	0.1833221037154887
  (0, 25464)	0.12399508683964489
  (0, 29137)	0.1611598924647531
  (0, 24418)	0.17001325611252707
  (0, 23212)	0.17974229527730723
  (0, 30041)	0.1611598924647531
  (0, 29650)	0.1951670832651365
  (0, 23253)	0.11818096973136863
  (0, 5149)	0.18147249173534674
  (0, 975)	0.13142966756625357
  (0, 1202)	0.05788886334551426
  (0, 21177)	0.1833221037154887
  (0, 1238)	0.03465540214110977
  (0, 19335)	0.17513520635418361
  (0, 10181)	0.1486646138988693
  (0, 2910)	0.11046857573745401
  (0, 27074)	0.15800227764002825
  (0, 2624)	0.10562294973544058
  (0, 4049)	0.067806465440421
  (0, 17733)	0.11869162784514985
  (0, 28138)	0.16672644228889758
  :	:
  (4802, 26724)	0.06809397308595068
  (4802, 18937)	0.0640212903261547
  (4802, 11719)	0.08180139518749079
  (4802, 29200)	0.07747795289570394
  (4802, 9175)	0.0768590349620255
  (4802, 

**COSINE SIMILARITY**

In [26]:
similarity = cosine_similarity(feature_vectors)
print(similarity) 

[[1.         0.03405403 0.03366926 ... 0.0198114  0.0312866  0.0070467 ]
 [0.03405403 1.         0.03105138 ... 0.03489247 0.02038452 0.01381278]
 [0.03366926 0.03105138 1.         ... 0.02802907 0.05202542 0.01180564]
 ...
 [0.0198114  0.03489247 0.02802907 ... 1.         0.03743513 0.03653328]
 [0.0312866  0.02038452 0.05202542 ... 0.03743513 1.         0.03078044]
 [0.0070467  0.01381278 0.01180564 ... 0.03653328 0.03078044 1.        ]]


Interaction with user

In [27]:
movie_name = input(' Please type your favourite movie name for which you want similar movies to be presented: ')

 Please type your favourite movie name : Batman


In [29]:
list_of_all_titles = movies_data['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
close_match = find_close_match[0]
print(close_match)


Batman


In [31]:
#Getting the index to the most related movie
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

1359


In [32]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.02640127771028294), (1, 0.03529185958379921), (2, 0.024656624180245685), (3, 0.2535220722236429), (4, 0.033146794183057035), (5, 0.06390339640818993), (6, 0.019392285503553833), (7, 0.021923779069946706), (8, 0.07288382756916427), (9, 0.1272449649118307), (10, 0.07473584941177826), (11, 0.030064942523285357), (12, 0.035557804990250984), (13, 0.015093081866816262), (14, 0.08477376607586717), (15, 0.037381746646056195), (16, 0.04728790278987786), (17, 0.05275841375160508), (18, 0.03938554507437587), (19, 0.03974060007861206), (20, 0.046748413059686994), (21, 0.05478940840591238), (22, 0.01751292280292204), (23, 0.014395408567208312), (24, 0.026180688501844192), (25, 0.029556711504739215), (26, 0.03027375997836447), (27, 0.024505130483753884), (28, 0.006729468058099508), (29, 0.014241008985305052), (30, 0.11580842644370104), (31, 0.019507535806830144), (32, 0.04469619217607497), (33, 0.011780589816218108), (34, 0.006320789836882832), (35, 0.041688495018396624), (36, 0.0614883209441

In [33]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(1359, 1.0000000000000002), (428, 0.2846556666048285), (210, 0.2642964061766604), (3, 0.2535220722236429), (119, 0.24376808707926778), (65, 0.20993673958843267), (299, 0.18790655467990086), (3854, 0.13287668011261405), (9, 0.1272449649118307), (30, 0.11580842644370104), (72, 0.10972063052024089), (1512, 0.10575759112878441), (1001, 0.10043578636312296), (1469, 0.09804796622673052), (1803, 0.0976536916960091), (579, 0.09721572451636665), (813, 0.09665907376756899), (4759, 0.09442467839587187), (41, 0.0939895539094683), (753, 0.09363038329468404), (3068, 0.09156554749351975), (2365, 0.08772001118053141), (2858, 0.08765376282663534), (4183, 0.08629237759059061), (800, 0.08605308839646578), (3819, 0.08601648848840883), (2381, 0.08596352339301476), (583, 0.08554023801688357), (870, 0.08522263956438654), (14, 0.08477376607586717), (1421, 0.08459883920290481), (1390, 0.08395661196326545), (1247, 0.08325040676509544), (623, 0.08185457777914963), (2265, 0.08137954376384073), (473, 0.0809417851

In [40]:
print('Movies suggested for according to the given input movie(top 10 most similar): \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<=10):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for according to the given input movie(top 10 most similar): 

1 . Batman
2 . Batman Returns
3 . Batman & Robin
4 . The Dark Knight Rises
5 . Batman Begins
6 . The Dark Knight
7 . Batman Forever
8 . Batman: The Dark Knight Returns, Part 2
9 . Batman v Superman: Dawn of Justice
10 . Spider-Man 2
